## MODULES IN USE

# don't print a new line at the start of the prompt
add_newline = false

format = """\
  $username\
  $directory\
  $git_branch\
  $git_state\
  $python\
  $status\
  $character\
  $jobs\
  """

[username]
show_always = true

[python]
symbol = " "
format = '[(${symbol}\($virtualenv\) )]($style)'
style = "bold blue"

# replace the "❯" symbol in the prompt with "➜" and show the exit code
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 1
#truncation_symbol = "…/"
#fish_style_pwd_dir_length = 1

[status]
format = "[$status]($style) "
disabled = false
