[theme]
name = "native"
[icons]
name = "awesome5"
[icons.overrides]
thermometer-full = "\uf2c7"
thermometer-empty = "\uf2cb"

[[block]]
block = "time"
format = "%I:%M %p %a %d %b %Y"
interval = 15
icons_format = ""

[[block]]
block = "net"
device = "wlan0"
interval = 3
hide_inactive = true
hide_missing = true
format = "{ssid} {signal_strength}"

[[block]]
block = "net"
device = "enp2s0"
interval = 3
hide_inactive = true
hide_missing = true
format = "{ip}"

[[block]]
block = "cpu"
interval = 5
format = "{utilization}"

[[block]]
block = "battery"
device = "BAT0"
format = "{percentage} {time}"
interval = 30
[block.theme_overrides]
warning_fg = "#E06C75"
critical_fg = "#BE5046"

[[block]]
block = "toggle"
text = "GAMMA"
command_state = "systemctl --user show --property=ActiveState wlsunset | grep '=active'"
command_on = "systemctl --user start wlsunset"
command_off = "systemctl --user stop wlsunset"
icon_on = "thermometer-full"
icon_off = "thermometer-empty"
