[theme]
name = "native"
[icons]
name = "awesome5"
[icons.overrides]
thermometer-full = "\uf2c7"
thermometer-empty = "\uf2cb"
cpu = "\uf2db"

[[block]]
block = "custom"
command = "~/.local/bin/srvstat || echo '\uf071'"
interval = 60
hide_when_empty = true
shell = "bash"

[[block]]
block = "pacman"
interval = 21600
format = "{pacman}"
format_singular = ""
format_up_to_date = ""
warning_updates_regex = "(age|apparmor|chromium|firefox|dash|sway|wlroots)"
critical_updates_regex = ""
hide_when_uptodate = true
on_click = "env CHECKUPDATES_DB='/tmp/checkup-db-proteus/' checkupdates | rofi -dmenu"

[[block]]
block = "time"
format = "%I:%M %p %a %d %b %Y"
interval = 15

[[block]]
block = "net"
device = "wlan0"
interval = 3
hide_inactive = true
hide_missing = true
format = "{ssid} {signal_strength}"

[[block]]
block = "net"
device = "enp2s0"
interval = 3
hide_inactive = true
hide_missing = true
format = "{ip}"

[[block]]
block = "cpu"
interval = 5
format = "{utilization}"

[[block]]
block = "battery"
device = "BAT0"
format = "{percentage} {time}"
interval = 30
[block.theme_overrides]
warning_fg = "#E06C75"
critical_fg = "#BE5046"

[[block]]
block = "toggle"
text = "GAMMA"
command_state = "systemctl --user show --property=ActiveState wlsunset | grep '=active'"
command_on = "systemctl --user start wlsunset"
command_off = "systemctl --user stop wlsunset"
icon_on = "thermometer-full"
icon_off = "thermometer-empty"

[[block]]
block = "custom"
command = "echo \uf011"
on_click = "doas -n /usr/sbin/systemctl `echo -e 'suspend\nreboot\npoweroff' | rofi -dmenu`"
interval = "once"
