#!/bin/sh
# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Ayush Agarwal <ayushnix at fastmail dot com>
#
# Permission to use, copy, modify, and /or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# -----------------------------------------------------------------------------
#
# this script serves as a pastebin for code, images, and other kinds of files
# meant to be shared publicly
#
# -----------------------------------------------------------------------------

# disable shellcheck warning about dynamic paths when sourcing files
# shellcheck disable=SC1091
if [ -f "$HOME/.local/bin/common-func.sh" ]; then
  . "$HOME"/.local/bin/common-func.sh
else
  printf "%s\n" "unable to find the library file for commonly used functions" >&2
  exit 1
fi

main() {
  if ! is_installed curl; then
    _die "curl is not installed"
  fi
  if ! is_installed fzf; then
    _die "fzf is not installed"
  fi

  services="\
0x0
paste.rs
clbin"

  txtbin="$(printf "%s" "$services" | fzf)"
  arg="${1:-/dev/stdin}"

  case "$txtbin" in
    0x0) curl -sF 'file=@-' https://0x0.st < "$arg" ;;
    paste.rs) curl --data-binary '@-' https://paste.rs < "$arg" ;;
    clbin) curl -sF 'clbin=<-' https://clbin.com < "$arg" ;;
  esac
}

main "$@"
