#!/bin/sh
#
# SPDX-License-Identifier: 0BSD
# Copyright (c) 2022 by Ayush Agarwal
# shellcheck disable=SC3043

# disable shellcheck warning about dynamic paths when sourcing files
# shellcheck disable=SC1091
if [ -f "$HOME/.local/bin/common-func.sh" ]; then
  . "$HOME"/.local/bin/common-func.sh
else
  printf "%s\n" "unable to find the library file for commonly used functions" >&2
  exit 1
fi

main() {
  local opt dep

  for dep in imv qrencode; do
    if ! is_installed "$dep"; then
      _die "error: $dep is not installed"
    fi
  done

  OPTIND=1
  while getopts ":s:h" opt; do
    case "$opt" in
      s) ssid="$OPTARG" ;;
      h)
        show_help
        exit 0
        ;;
      \?)
        printf "%s\n" "invalid option! -$OPTARG" >&2
        exit 1
        ;;
      :)
        printf "%s\n" "-$OPTARG requires an argument" >&2
        exit 1
        ;;
    esac
  done
  shift "$((OPTIND - 1))"

  while [ -z "$ssid" ]; do
    printf "%s" "ssid: "
    read -r ssid
  done

  stty -echo
  while [ -z "$pass" ]; do
    printf "%s" "password: "
    read -r pass
  done
  stty echo

  # make sure that you don't have a colon character ':' in the password
  qrencode -t SVG -o - "WIFI:T:WPA;S:$ssid;P:$pass;;" | imv -

  unset -v opt dep
}

main "$@"
