#!/bin/sh

# disable shellcheck warning about dynamic paths when sourcing files
# shellcheck disable=SC1091
if [ -f "$HOME/.local/bin/common-func.sh" ]; then
  . "$HOME"/.local/bin/common-func.sh
else
  printf "%s\n" "unable to find the ayushnix library file" >&2
  exit 1
fi

if ! is_installed identify; then
  _die "imagemagick is not installed, unable to proceed"
fi

for asprat in "$@"; do
  identify -format "%[fx:w/h]: %M\n" "$asprat" 2> /dev/null \
    || _die "unable to find the aspect ratio of the file '$asprat'"
done
