#!/bin/sh
# remove package from local repository used by aurutils

if [ "$#" -eq 0 ]; then
  printf 'usage: aur remove package [package ...]\n' >&2
  exit 1
fi

aur repo --list-path | while read -r repo_path; do
  repo-remove "$repo_path" "$@"
  paccache -c "${repo_path%/*}" -rvk0 "$@"
done
