#!/bin/sh

monitor="eDP-1"

if grep -q open /proc/acpi/button/lid/LID/state; then
  swaymsg output "$monitor" enable || _die "unable to enable $monitor"
else
  swaymsg output "$monitor" disable || _die "unable to disable $monitor"
fi
