#!/bin/bash

# shellcheck source=./bwrap_init
. ~/.local/bin/bwrap_init

_access_downloads
_read_only_diff "$XDG_CONFIG_HOME/chromium-flags.conf" "$bwrap_home/.config/chromium-flags.conf"
_read_write_diff "$XDG_CONFIG_HOME/chromium" "$bwrap_home/.config/chromium"
_gui
_network
_gpu
_dbus
_audio

run_jail
