#!/bin/bash

# shellcheck source=./bwrap_init
. ~/.local/bin/bwrap_init

_read_only_diff "$XDG_CONFIG_HOME/zathura" "$bwrap_home/.config/zathura"
_read_only_all "/data/downloads" "/data/professional"
_gui

run_jail
