#!/bin/bash

# shellcheck source=./bwrap_init
. ~/.local/bin/bwrap_init "$@"

gen_machine_id() {
  local machineid
  machineid="$(openssl rand -hex 16)"
  printf "%s\n" "$machineid" > "$HOME/.sandbox/$executable/machine-id"
}

_env "MOZ_ENABLE_WAYLAND" "1"
gen_machine_id
_read_only_diff "$HOME/.sandbox/$executable/machine-id" "/etc/machine-id"
_access_downloads
_read_write_diff "$HOME/.mozilla" "$bwrap_home/.mozilla"
_gui
_network
_gpu
_dbus
_audio

run_jail
