#!/bin/bash
#
# A simple and dirty alternative to etckeeper that doesn't need root
# permissions assuming that the files and directories to be copied over to
# XDG_CONFIG_HOME have a umask of 022

if ! command -v rsync > /dev/null 2>&1; then
  printf '%s\n' "unable to proceed, rsync isn't installed" >&2
  exit 1
fi

backup_files=(
  "pacman.d/hooks/100-systemd-boot.hook"
  "pacman.d/hooks/101-export-explicit-pkgs.hook"
  "pacman.d/hooks/101-export-optional-pkgs.hook"
  "sysctl.d/21-networking-performance.conf"
  "sysctl.d/22-stack-harden.conf"
  "sysctl.d/23-virtual-memory.conf"
  "sysctl.d/50-kernel-harden.conf"
  "sysctl.d/52-coredump.conf"
  "udev/rules.d/60-ioschedulers.rules"
  "interception/udevmon.d/caps2esc.yaml"
  "tmpfiles.d/cursor.conf"
  "modprobe.d/thinkpad_acpi.conf"
  "ssh/sshd_config"
  "X11/Xwrapper.config"
  "X11/xorg.conf.d/10-block-tty-dont-kill-x.conf"
  "X11/xorg.conf.d/20-amdgpu.conf"
  "X11/xorg.conf.d/30-disable-dpms.conf"
  "makepkg.conf"
  "mkinitcpio.conf"
  "pacman.conf"
  "systemd/coredump.conf"
  "systemd/journald.conf"
  "systemd/system/user@1000.service.d/override.conf"
  "systemd/system/getty@tty1.service.d/override.conf"
  "systemd/system/sshd.service.d/override.conf"
  "systemd/system/syncthing@proteus.service.d/override.conf"
  "systemd/logind.conf.d/neptune.conf"
)

for file in "${backup_files[@]}"; do
  rsync -Rt /etc/"$file" "$XDG_CONFIG_HOME"/ || {
    printf '%s\n' "unable to copy $file" >&2
    exit 1
  }
done

unset -v file backup_files
