#!/bin/bash
#
# A simple and dirty alternative to etckeeper that doesn't need root
# permissions assuming that the files and directories to be copied over to
# XDG_CONFIG_HOME have a umask of 022

set -uo pipefail
readonly PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
export PATH
umask 077

if ! command -v rsync > /dev/null 2>&1; then
  printf '%s\n' "unable to proceed, rsync isn't installed" >&2
  exit 1
fi

backup_files=(
  "dnscrypt-proxy/blocked-ips.txt" "dnscrypt-proxy/cloaking-rules.txt"
  "dnscrypt-proxy/dnscrypt-proxy.toml" "dnscrypt-proxy/domains-blocklist.conf"
  "pacman.d/hooks/100-systemd-boot.hook" "pacman.d/hooks/101-export-explicit-pkgs.hook"
  "pacman.d/hooks/101-export-optional-pkgs.hook" "sysctl.d/21-networking-performance.conf"
  "sysctl.d/22-stack-harden.conf" "sysctl.d/23-virtual-memory.conf"
  "sysctl.d/50-kernel-harden.conf" "sysctl.d/52-coredump.conf"
  "systemd/coredump.conf" "systemd/journald.conf" "udev/rules.d/60-ioschedulers.rules"
)

for file in "${backup_files[@]}"; do
  rsync -Rpt /etc/"$file" "$XDG_CONFIG_HOME"/ || {
    printf '%s\n' "unable to copy $file" >&2
    exit 1
  }
done

unset -v file backup_files
